<?php

declare(strict_types=1);

namespace CrazyGoat\Elephas;

/**
 * TigerBeetle create account status codes.
 *
 * Maps to TB_CREATE_ACCOUNT_STATUS in tb_client.h.
 */
enum CreateAccountStatus: int
{
    case CREATED = 0xFFFFFFFF;
    case LINKED_EVENT_FAILED = 1;
    case LINKED_EVENT_CHAIN_OPEN = 2;
    case TIMESTAMP_MUST_BE_ZERO = 3;
    case IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE = 4;
    case IMPORTED_EVENT_TIMESTAMP_MUST_NOT_BE_ZERO = 5;
    case IMPORTED_EVENT_TIMESTAMP_MUST_NOT_BE_IN_THE_FUTURE = 6;
    case RESERVED_FIELD = 7;
    case RESERVED_FLAG = 8;
    case ID_MUST_NOT_BE_ZERO = 9;
    case ID_MUST_NOT_BE_INT_MAX = 10;
    case EXISTS_WITH_DEBITS = 11;
    case EXISTS_WITH_CREDITS = 12;
    case EXISTS_WITH_PENDING_DEBITS = 13;
    case EXISTS_WITH_PENDING_CREDITS = 14;
    case EXISTS_WITH_POSTS = 15;
    case EXISTS_WITH_VOIDS = 16;
    case MUTUALLY_EXCLUSIVE_FLAGS = 17;
    case OVERFLOWS_DEBITS = 18;
    case OVERFLOWS_CREDITS = 19;
    case OVERFLOWS_DEBITS_PENDING = 20;
    case OVERFLOWS_CREDITS_PENDING = 21;
    case OVERFLOWS_DEBITS_POSTED = 22;
    case OVERFLOWS_CREDITS_POSTED = 23;
    case OVERFLOWS_TIMEOUT = 24;
    case EXCEEDS_CREDITS = 25;
    case EXCEEDS_DEBITS = 26;
    case IMPORTED_EVENT_TIMESTAMP_MUST_BE_IN_THE_FUTURE = 27;
}
