<?php

declare(strict_types=1);

namespace CrazyGoat\Elephas;

/**
 * TigerBeetle create transfer status codes.
 *
 * Maps to TB_CREATE_TRANSFER_STATUS in tb_client.h.
 */
enum CreateTransferStatus: int
{
    case CREATED = 0xFFFFFFFF;
    case LINKED_EVENT_FAILED = 1;
    case LINKED_EVENT_CHAIN_OPEN = 2;
    case TIMESTAMP_MUST_BE_ZERO = 3;
    case IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE = 4;
    case IMPORTED_EVENT_TIMESTAMP_MUST_NOT_BE_ZERO = 5;
    case IMPORTED_EVENT_TIMESTAMP_MUST_NOT_BE_IN_THE_FUTURE = 6;
    case RESERVED_FLAG = 7;
    case ID_MUST_NOT_BE_ZERO = 8;
    case ID_MUST_NOT_BE_INT_MAX = 9;
    case DEBITS_ACCOUNTS_MUST_DIFFER = 10;
    case PENDING_ID_MUST_BE_ZERO = 11;
    case PENDING_ID_MUST_NOT_BE_ZERO = 12;
    case PENDING_ID_MUST_NOT_BE_INT_MAX = 13;
    case PENDING_ID_MUST_BE_DIFFERENT = 14;
    case EXCEEDS_PENDING_TRANSFER_AMOUNT = 15;
    case EXCEEDS_PENDING_TRANSFER_BALANCE = 16;
    case PENDING_TRANSFER_HAS_DIFFERENT_DEBIT_ACCOUNT_ID = 17;
    case PENDING_TRANSFER_HAS_DIFFERENT_CREDIT_ACCOUNT_ID = 18;
    case PENDING_TRANSFER_HAS_DIFFERENT_CURRENCY = 19;
    case PENDING_TRANSFER_ALREADY_POSTED = 20;
    case PENDING_TRANSFER_ALREADY_VOIDED = 21;
    case PENDING_TRANSFER_EXPIRED = 22;
    case MUTUALLY_EXCLUSIVE_FLAGS = 23;
    case BALANCING_DEBIT_AND_CREDIT_ACCOUNTS_MUST_DIFFER = 24;
    case BALANCING_DEBIT_AND_CREDIT_ACCOUNTS_MUST_HAVE_THE_SAME_CURRENCY = 25;
    case OVERFLOWS_DEBITS = 26;
    case OVERFLOWS_CREDITS = 27;
    case OVERFLOWS_DEBITS_PENDING = 28;
    case OVERFLOWS_CREDITS_PENDING = 29;
    case OVERFLOWS_DEBITS_POSTED = 30;
    case OVERFLOWS_CREDITS_POSTED = 31;
    case OVERFLOWS_TIMEOUT = 32;
    case EXCEEDS_CREDITS = 33;
    case EXCEEDS_DEBITS = 34;
    case CLOSING_TRANSFER_MUST_BE_PENDING = 35;
    case IMPORTED_EVENT_TIMESTAMP_MUST_BE_IN_THE_FUTURE = 36;
}
